name: Compressed Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mister-ben/compressed-size-action@feat-percent
        with:
          percent-decimal-places: 2